spring:
  application:
    name: demo

  datasource:
    url: jdbc:mysql://localhost:3306/university_manager
    username: root
    password: N@mphpmyadmin2004

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080